spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://ls-7f60874ca0f38bb4fec0c8cc7c593d9e21f42e70.cyfldpxwkomt.ap-northeast-2.rds.amazonaws.com:3306/i4blog?serverTimeZone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dbmasteruser
    password: or!|82:l~Sf9v+K1E=;tNYsr6dzOFAp[

  servlet:
    multipart:
      enabled: true
      location: /var/upload
      max-request-size: 30MB
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: bark6256@gmail.com
    password: izbmomedxqhnpwvc
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
      force: true

mybatis:
  mapper-locations:
    - classpath:mapper/**/**.xml
  configuration:
    map-underscore-to-camel-case: true

org:
  zerock:
    upload:
      path: \src\main\resources\static
openai:
  model: gpt-3.5-turbo-16k-0613
  api:
    url: https://api.openai.com/v1/chat/completions
    key: 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
