spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/i4blog?serverTimeZone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asd1234
  servlet:
    multipart:
      enabled: true
      location: C:\\upload
      max-request-size: 30MB
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: bark6256@gmail.com
    password: izbmomedxqhnpwvc
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
      force: true

mybatis:
  mapper-locations:
    - classpath:mapper/**/**.xml
  configuration:
    map-underscore-to-camel-case: true

org:
  zerock:
    upload:
      path: \src\main\resources\static
openai:
  model: gpt-3.5-turbo-16k-0613
  api:
    url: https://api.openai.com/v1/chat/completions
    key: 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